import React, { useState } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import FormControl from '@mui/material/FormControl';
import Button from '@mui/material/Button';

import styles from '../styles/Home.module.css'
import { useAbly } from "../ably";

function Home() {
  const [comments, setComments] = useState([]);
  const [username, setUsername] = useState("");
  const [comment, setComment] = useState("");

   const [channel, ably] = useAbly("test", (message) => {
     setComments([...comments, message.data])
   });

  const submitComment = () => {
    channel.publish({
      name: "comment",
      data: {
        username,
        comment
      }
    });
    setUsername("")
    setComment("")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid>
      {
        comments.length > 0 ? comments.map((comment) => {
          return(
            <div>{comment.comment} {comment.username}</div>
          )
        }):
        <div>No comments at the moment</div>
      }
      </Grid>

      <FormControl>
        <Grid container spacing={2}>
          <Grid item xs={12}>
            <TextField
              required
              id="username"
              name="username"
              label="Username"
              variant="outlined"
              value={username}
              onChange={(event) => setUsername(event.target.value)}
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              required
              id="comment"
              name="comment"
              label="Comment"
              variant="outlined"
              multiline
              maxRows={4}
              value={comment}
              onChange={(event) => setComment(event.target.value)}
            />
          </Grid>
          <Grid item xs={12}>
           <Button variant="contained" onClick={submitComment}>Submit</Button>
          </Grid>
        </Grid>
      </FormControl>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;
